### ISSUE TITLE
rounding error in division operation

### ISSUE THREAD

**Issue by shimshon4M** [facebookresearch/CrypTen#102]
I tried arithmetic operations referring tutorials.
```
x_enc=crypten.cryptensor([1.0,2.0,3.0])
y=3
y_enc = crypten.cryptensor(y)

z_enc1=x_enc/y
z_enc2=x_enc/y_enc
print(z_enc1.get_plain_text())
print(z_enc2.get_plain_text())
print(z_enc1.get_plain_text()==z_enc2.get_plain_text())
```

Divided by 3, the results of public and private calculation are different.
Is this correct behavior?
```
tensor([0.3333, 0.6667, 1.0000])
tensor([0.3334, 0.6667, 1.0001])
tensor([False, False, False])
```

**Comment by knottb** [comment]
Because of how reciprocals are computed internally, all divisions by encrypted values are approximations. If you would like to improve the precision of this division you have a few options - 

1.) Use `reciprocal` with the `nr_iters` keyword argument (default value is 10)

`z_enc2 = x_enc * y_enc.reciprocal(nr_iters=15)`

2.) Use a better initialization for the reciprocal if one is known. By default, we use an exponential decay function with specific parameters to approximate an initial guess for our Newton-Raphson iterations since this is a good initial approximation for a general input where the domain is unknown. To specify your own initial guess you can use:

`z_enc2 = x_enc * y_enc.reciprocal(initial=your_initialization)`

3.) Increase the fixed point precision used by the encoder. We use a FixedPointEncoder with a default of 16 bits of precision after the fixed point (i.e. we quantize with granularity 0.00001525878). You can increase this to e.g. 20 bits by using the following:

`crypten.encoder.set_default_precision(20)`


Let me know you have any additional questions.

**Comment by dronemist** [comment]
I tried running this but it no longer works. How do we increase the ``nr_iters`` of reciprocal in the current version of Crypten
