### ISSUE TITLE
CrypTen Communication costs question

### ISSUE THREAD

**Issue by venetahar** [facebookresearch/CrypTen#106]
Hi,

Apologies if this is a trivial question. I am using CrypTen to perform private inference in a 2-party setting and I wanted to examine the communication costs. I have increased the logging level to INFO and I am using the [print_communication_stats](https://github.com/facebookresearch/CrypTen/blob/d6f221b7d6d12b5b2626a1547cdd617cf97a9b0b/crypten/__init__.py#L50
) method to do this. It seems to be working as I am getting the following output: 

`INFO:root:====Communication Stats====`
`INFO:root:====Communication Stats====`
`INFO:root:Rounds: 37`
`INFO:root:Bytes : 8289040`
`INFO:root:Rounds: 37`
`INFO:root:Bytes : 8289040`

I believe it's reported twice because I have a world size of 2 so each process is printing the stats. However, when it comes to interpreting this I am slightly unsure about one thing. 

Is the total communication cost 8289040 + 8289040 = 16,578,080 bytes or is each process already reporting the total communication cost between the parties: 8289040 bytes

Thanks a lot in advance! 
 Veneta

**Comment by knottb** [comment]
Each process reports the number of bytes handled by its own communicator. For example, if an 8-byte value is sent by party 0 and received by party 1, party 0 and party 1 each log 8 bytes.

We can improve the way this is reported by adding a rank tag to the output since a user running CrypTen on one machine using multiple processes will see the values reported multiple times as you are getting.

**Comment by venetahar** [comment]
Ah that makes sense. Thanks a lot for quick response!
