### ISSUE TITLE
SMPC for Tree Based Models

### ISSUE THREAD

**Issue by akkolwalkar** [facebookresearch/CrypTen#213]
Is it possible to get SMPC working on Tree Based Models like Decision Tree or Ensemble models?

**Comment by knottb** [comment]
It is possible, though not currently supported directly in CrypTen. One would have to implement their own tree-based model using CrypTen as a computation library. We are looking into adding support here in the future, but don't have short-term plans to include it.

As a note, trees can be much less efficient in SMPC than in plaintext. This is because in encrypted computations, we cannot evaluate logic to decide which branch of a tree to compute. Instead, in SMPC, one must compute the result for every leaf and multiplex between them using binary evaluation of logic (and multiplying the one-hot result by the vector of leaf evaluations).

This means that tree-based optimizations used for various algorithms no longer have the same computational advantages in SMPC. That is, a tree-based algorithm that uses branching to achieve O(log N) complexity will instead have O(N) complexity, where N is the number of nodes in the tree. For shallow trees, this difference is minimal (so ensemble models with shallow trees can potentially work well). However, larger trees will likely be far less efficient to run in SMPC when compared with plaintext.

**Comment by akkolwalkar** [comment]
So for Tree Based and Ensemble model which is the best relatively in terms
of performance? SMPC, TEE's or HE's?

**Comment by knottb** [comment]
It really depends on the application. There are advantages and disadvantages to each of these:

**SMPC:** Can be very fast if your network connection is low-latency. Requires all parties to be online with stable connections throughout the computation. Softward-based solution.

**TEE:** Can also be fast, however TEE's require specialized hardware which may or may not be available depending on your application. More and more, TEE's are becoming available on cloud services. My understanding is there is a lot of variance in performance (and memory limitations) depending on threat model.

**HE:** Almost always slow. Depending on the protocol, this is either because you are operating in a large finite field or because encryption requires some level of bit-decomposition. Additionally, SWHE or leveled HE only allows a small number of computations, and FHE can become prohibitively expensive due to bootstrapping.

I'm mostly familiar with MPC, so my explanations for TEE's and HE may be a bit outdated or missing some nuance, but this is my general understanding.

**Comment by psy-mas** [comment]
> It is possible, though not currently supported directly in CrypTen. One would have to implement their own tree-based model using CrypTen as a computation library. We are looking into adding support here in the future, but don't have short-term plans to include it.
> 
> As a note, trees can be much less efficient in SMPC than in plaintext. This is because in encrypted computations, we cannot evaluate logic to decide which branch of a tree to compute. Instead, in SMPC, one must compute the result for every leaf and multiplex between them using binary evaluation of logic (and multiplying the one-hot result by the vector of leaf evaluations).


Hello, my greetings. Any ideas to implement a single CART decision trees using crypten? I really don't know how to implement Division & Argmax function using arithmetic-ss.Furthermore,in the scenario where the data is in a vertical partition form, is it possible to compute Gini for the party who does not hold the labels if the raw labels stay on the holder?
