### ISSUE TITLE
Issue with division operation

### ISSUE THREAD

**Issue by chenxiliu1998** [facebookresearch/CrypTen#224]
Hello, I am having issues with the division operations.  I am having incorrect results when I do division in my code. And I did some tests and found that when the number is quite large, the results would be wrong, as shown in the figure. I want to know how I can solve this problem.
![image](https://user-images.githubusercontent.com/38418073/109934935-00b4ee80-7d08-11eb-820c-a6e7723d9130.png)

**Comment by knottb** [comment]
Because of the limitations of encryption, functions in CrypTen are all constructed from compositions of linear operations and logical comparisons. Because of this, some functions are implemented using functional approximations. In this case, we use Newton-Raphson iterations to implement the `reciprocal` function.

Because of how Newton-Raphson (and other iterative methods work), convergence is only guaranteed within a range of inputs. The range for `reciprocal` is approximately [-500, 500]. So, the denominator of any division (by a cryptensor) must be within this range.

Here, you set the value of `a` to `666`, which is outside of this range. If you reduce this value, division should work. We understand that this puts limitations on the kinds of inputs you can use, but there is currently no known way to make this work for all inputs and we had to make design choices here.
