### ISSUE TITLE
Crypten' has no attribute 'print

### ISSUE THREAD

**Issue by kamathhrishi** [facebookresearch/CrypTen#226]
```
AttributeError                            Traceback (most recent call last)
<ipython-input-5-b53a8eee043c> in <module>
      9 z_enc1 = x_enc + y      # Public
     10 z_enc2 = x_enc + y_enc  # Private
---> 11 crypten.print("\nPublic  addition:", z_enc1.get_plain_text())
     12 crypten.print("Private addition:", z_enc2.get_plain_text())
     13 

AttributeError: module 'crypten' has no attribute 'print'

```

I tried running the tutorial notebook and got this error. Is this a problem on my system or Crypten has removed the print feature. If its the latter I would be happy to refractor the notebooks accordingly and submit a PR. 

Maybe also add notebooks to tests to ensure its in sync with the codebase changes?

**Comment by knottb** [comment]
The print function is defined here:
https://github.com/facebookresearch/CrypTen/blob/master/crypten/__init__.py#L462

I think this issue is likely due to the pip version being quite old, whereas this print functionality is fairly new. We plan to release a new pip version soon.

For now, this is unlikely to work when installing from pip. Instead, you would have to run from source by using the following procedure:

1. Download CrypTen from github using any method (click the "Code" dropdown from https://github.com/facebookresearch/CrypTen)
3. In a terminal, install using `pip install -e /path/to/CrypTen`

Once this is done, this tutorial should work properly. We are working on making this a more streamlined process.

**Comment by kamathhrishi** [comment]
Alright then thank you. I guess I am okay since I am able to train models as usual.
