### ISSUE TITLE
How does plain_text works

### ISSUE THREAD

**Issue by dronemist** [facebookresearch/CrypTen#233]
Hi! 
I had a doubt regarding how get_plain_text() works. Does this involve a round of communication between all the processes in the process pool, because if not wouldn't it be a security flaw if a user could just use that function to get the decrypted value? Also, I wasn't able to understand the working of the multiply operation, in the sense that how many rounds of communication between parties it requires?

**Comment by lvdmaaten** [comment]
The `get_plain_text()` function essentially performs an all-reduce on the relevant tensor. This requires all the processes (except the TTP, if it exists) to participate in the communication, that is, all parties must agree to share their secret share of the tensor. If one party calls `get_plain_text()` but the other parties do not, then that party's process will simply halt forever (because it is waiting for the other parties to call `get_plain_text()` as well).

**Comment by dronemist** [comment]
Ah I see, thanks
