### ISSUE TITLE
Support for pytorch based libraries

### ISSUE THREAD

**Issue by ashish180199** [facebookresearch/CrypTen#247]
Can `crypten.nn.from_pytorch` convert models which are not of `torch.nn` type. We wanted to work with [gpytorch](https://github.com/cornellius-gp/gpytorch) and were wondering what's the best way to covert and use general torch models to CryTen models. This is the error we face - 
```
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: MultivariateNormal
```

[This](https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/distributions/multivariate_normal.py) is the code for the class MultivariateNormal.

**Comment by lvdmaaten** [comment]
The importing from PyTorch relies on PyTorch's ONNX exporter (`torch.onnx.export()`) to obtain a computation graph that we then try to import into CrypTen. I believe the error you are seeing is a limitation of PyTorch's ONNX exporter. Given that PyTorch is focusing on TorchScript rather than ONNX, I don't know if there is a path to this being fixed.

Even if the ONNX export succeeds, the importing of the ONNX graph into CrypTen can be tricky for somewhat more esoteric operations -- this is something we are actively working on. Note that ONNX does not support dynamic graphs, so those cannot be imported (also note that dynamic graphs are typically inefficient in secure MPC because all code paths need to be traversed in order to not leak information).

Your best bet may be to port GPyTorch to CrypTen explicitly.

**Comment by knottb** [comment]
Also, CrypTen also does not have support currently for `Distribution`s outside of uniform (using `rand()`) and normal (using `randn()`). Any other distribution type would have to be implemented from those or generated in plaintext and encrypted later.
