### ISSUE TITLE
Communication cost

### ISSUE THREAD

**Issue by dronemist** [facebookresearch/CrypTen#255]
I am sorry if I am missing something trivial, but after setting the logging level to info and using `print_communication_stats()`, I am getting the bytes sent and received as 0, Is there something else we need to do before we can get the communication costs?

Thanks in advance :)

**Comment by lvdmaaten** [comment]
The `Communicator` base class implements [this decorator](https://github.com/facebookresearch/CrypTen/blob/2188ed26dcd45eb8c431e038308f36356b12fa60/crypten/communicator/communicator.py#L179) that tracks the number of communication rounds, the communication time, and the number of bytes communicated. That decorator is then used in all the major communication primitives in the `DistributedCommunicator` ([example](https://github.com/facebookresearch/CrypTen/blob/2188ed26dcd45eb8c431e038308f36356b12fa60/crypten/communicator/distributed_communicator.py#L110)). 

I just noticed that the `InProcessCommunicator` does not use the logging decorator though, so that seems something worth fixing. Is that the communicator you were using?

**Comment by dronemist** [comment]
I am using `mpc.run_multiprocess`, which I checked creates `DistributedCommunicator`, I am trying to train a GCN in `crypten`, and have the following function
```python
import crypten.mpc as mpc
import crypten.communicator as comm
import logging
logging.getLogger().setLevel(logging.INFO)

@mpc.run_multiprocess(world_size=num_parties)
def run_encrypted_training():
    # I want to measure all communications in this function
    ...
    comm.get().print_communication_stats()
   
```
This gives the following output:
```
INFO:root:==================
INFO:root:DistributedCommunicator with rank 0
INFO:root:==================
INFO:root:==================
INFO:root:DistributedCommunicator with rank 1
INFO:root:==================
INFO:root:==================
INFO:root:DistributedCommunicator with rank 2
INFO:root:==================
INFO:root:Added key: store_based_barrier_key:1 to store for rank: 2
INFO:root:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:root:Added key: store_based_barrier_key:1 to store for rank: 1
INFO:root:Added key: store_based_barrier_key:2 to store for rank: 0
INFO:root:Added key: store_based_barrier_key:2 to store for rank: 2
INFO:root:Added key: store_based_barrier_key:2 to store for rank: 1
INFO:root:Added key: store_based_barrier_key:3 to store for rank: 1
INFO:root:Added key: store_based_barrier_key:3 to store for rank: 0
INFO:root:Added key: store_based_barrier_key:3 to store for rank: 2
INFO:root:Added key: store_based_barrier_key:4 to store for rank: 0
INFO:root:Added key: store_based_barrier_key:4 to store for rank: 1
INFO:root:Added key: store_based_barrier_key:4 to store for rank: 2
INFO:root:World size = 3
INFO:root:World size = 3
INFO:root:World size = 3
INFO:root:====Communication Stats====
INFO:root:Rounds: 0
INFO:root:Bytes : 0
INFO:root:Comm time: 0
INFO:root:==================
```
Do I also need to add `@_logging` decorator above this function?

**Comment by dronemist** [comment]
@lvdmaaten Hi! I am working on a deadline, any help on this would be highly appreciated

**Comment by lvdmaaten** [comment]
I see. That means you are using the `[InProcessCommunicator](https://github.com/facebookresearch/CrypTen/blob/2188ed26dcd45eb8c431e038308f36356b12fa60/crypten/communicator/in_process_communicator.py)`.

In order to fix this bug, you need to decorate with `@_logging` every function in `[InProcessCommunicator](https://github.com/facebookresearch/CrypTen/blob/2188ed26dcd45eb8c431e038308f36356b12fa60/crypten/communicator/in_process_communicator.py)` that is decorated with `@_logging` in `[DistributedCommunicator](https://github.com/facebookresearch/CrypTen/blob/2188ed26dcd45eb8c431e038308f36356b12fa60/crypten/communicator/distributed_communicator.py#L110)`. Then your stats-logging code should work (hopefully!).

Please feel free to submit a PR if it works for you.

**Comment by dronemist** [comment]
Hi! I added `@_logging` to `InProcessCommunicator` but that didn't seem to solve the problem. I later realised that I was using `DistributedCommunicator` but I also had to set `verbosity` to `True` to log communication (sorry for the inconvenience). Still, I got the communication rounds as well as bytes correctly (I guess), but the communication time is negative. Could you give me an example of when exactly do we `set_verbosity` to True and when do we call the function to get the `communication_stats`? Currently, I am doing something like this 
```python
import crypten.mpc as mpc
import crypten.communicator as comm
import logging
logging.getLogger().setLevel(logging.INFO)

@mpc.run_multiprocess(world_size=num_parties)
def run_encrypted_training():
    comm.get().set_verbosity(True)
    # I want to measure all communications in this function
    ...
    comm.get().print_communication_stats()
```

My output is
```
INFO:root:====Communication Stats====
INFO:root:Rounds: 775
INFO:root:Bytes : 474809344
INFO:root:Comm time: -0.0027206179999472724
INFO:root:==================
```
And thank you so much for the help.

**Comment by knottb** [comment]
I was able to replicate this issue - seems to be an issue within the `timeit.timeit()` method. I'll make a PR shortly that modifies this to `timeit.default_timer()`, which seems to perform as expected. If you'd like to implement this in your code sooner, you can change `timeit.timeit()` calls to `timeit.default_timer()` calls here:

https://github.com/facebookresearch/CrypTen/blob/master/crypten/communicator/communicator.py#L204-L206
