### ISSUE TITLE
The relationship between Privacy Preserving Machine Learning and Federated Learning

### ISSUE THREAD

**Issue by napoay** [facebookresearch/CrypTen#276]
As described in the README, "CrypTen is a framework for Privacy Preserving Machine Learning built on PyTorch."

One question that confuses me is，what is the difference  between **Privacy Preserving Machine Learning** and **Federated Learning**?

I try my best to find papers and materials to verify their relationship , but I do not get an accurate conclusion.

To the best of my knowledge, I think Federated Learning is a subset of Privacy Preserving Machine Learning. 

 Is that right?

**Comment by lvdmaaten** [comment]
Federated learning one of several paradigms for privacy-preserving machine learning that combines secure multi-party computation with computation on (large numbers of) edge devices. Specifically, federated learning computes local gradient updates on edge devices (in the clear) and then performs secure aggregation of these updates; the aggregated updates are then revealed to a central aggregator that can apply them to the model. One could certainly implement a secure aggregation protocol using CrypTen, but CrypTen is not optimized for such use cases: there exist better, custom secure aggregation protocols for federated learning that may be better used instead (for example, as implemented in PyGrid).

Closing this issue because questions like this are probably better suited for StackOverflow or Quora.
