### ISSUE TITLE
Questions about the encryption model

### ISSUE THREAD

**Issue by MtifyC** [facebookresearch/CrypTen#279]
##  Feature

With Tutorials I learn that we will need to work with encrypted data and encrypted models.The process of encrypting the data is also detailed: it is essentially done by two secret sharing protocols, which split the data into N pieces and send them to N parties.
My question is is it necessary to encrypt the model? What are the rules of encrypting the model? How does it do it?

## Alternatives

I guess whether the split of the data and the split of the model have to be consistent, i.e. they have to perform the same encryption before they can be run together?But how is that guaranteed, or am I wrong?

**Comment by knottb** [comment]
In theory, the model does not need to be encrypted so long as all parties have access to the weights. In the secret-sharing protocol, multiplications can happen either `encrypted * encrypted` or `encrypted * unencrypted` so long as the unencrypted parts are held by all parties (and `unencrypted * unencrypted` can be done trivially without secret-sharing). Model weights are just parameters that are multiplied by some other values.

In practice, for implementation reasons, we do not support unencrypted weights within models. The reason for this is a bit complicated, but it is because some details of our implementation make it difficult to add support for this. However, it is not at all impossible in theory.

The next question is then why encrypt the model? There are several reasons to do so:

1. Private Training: During training, if model weights are revealed during each batch update, the differential in model weights between batches can reveal a lot of information about the data.
2. Model hiding: A model may be proprietary or data used to train the model may be private.


Note that if the model is held by all parties, any party can perform inference locally, defeating the purpose of using MPC in many cases.
