### ISSUE TITLE
Training on multiple machines with different dataset.

### ISSUE THREAD

**Issue by veryhannibal** [facebookresearch/CrypTen#296]
I run Alice and Bob on two machines respectively. I set Environment variables as blow.
Alice: {
    "WORLD_SIZE": "2",
    "RANK": "0",
    "RENDEZVOUS": "env://",
    "MASTER_ADDR": "192.168.0.100",
    "MASTER_PORT": "9001",
    "DISTRIBUTED_BACKEND": "gloo",
} 

Bob:
 {
    "WORLD_SIZE": "2",
    "RANK": "0",
    "RENDEZVOUS": "env://",
    "MASTER_ADDR": "192.168.0.100",
    "MASTER_PORT": "9001",
    "DISTRIBUTED_BACKEND": "gloo",
}

But I got the error from Bob:
/opt/anaconda3/envs/crypten/bin/python3.7 /Users/lile18/Desktop/work/crypten_test/test4.py
Traceback (most recent call last):
  File "/Users/lile18/Desktop/work/crypten_test/test4.py", line 62, in <module>
    crypten.init()
  File "/Users/lile18/Desktop/work/crypten_test/crypten/__init__.py", line 63, in init
    comm._init(use_threads=False, init_ttp=crypten.mpc.ttp_required())
  File "/Users/lile18/Desktop/work/crypten_test/crypten/communicator/__init__.py", line 32, in _init
    cls.initialize(rank, world_size, init_ttp=init_ttp)
  File "/Users/lile18/Desktop/work/crypten_test/crypten/communicator/distributed_communicator.py", line 98, in initialize
    cls.instance = DistributedCommunicator(init_ttp=init_ttp)
  File "/Users/lile18/Desktop/work/crypten_test/crypten/communicator/distributed_communicator.py", line 59, in __init__
    rank=self.rank,
  File "/opt/anaconda3/envs/crypten/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 520, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/anaconda3/envs/crypten/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 199, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Connection reset by peer.

**Comment by knottb** [comment]
If you look at your environment variables, both parties have the same rank (rank 0). This will mean that the connection won't establish properly. Instead, you want one party to have rank 0 and one party to have rank 1.

It is likely that your error is a timeout due to connection not being established.

**Comment by veryhannibal** [comment]
> If you look at your environment variables, both parties have the same rank (rank 0). This will mean that the connection won't establish properly. Instead, you want one party to have rank 0 and one party to have rank 1.
> 
> It is likely that your error is a timeout due to connection not being established.

Sorry, I made a mistake while pasting the code, actually I set one to be 0 and one to be 1.  But I got the above error.

**Comment by knottb** [comment]
It looks like this is because you are using `"RENDEZVOUS": "env://"`. This means your machine uses the local environment as your init_method for torch.distributed. In order to connect torch.distributed connections across machines, you will need to use another init_method. Note that `RENDEZVOUS` is just another name for `init_method` here. See [torch.distributed documentation](https://pytorch.org/docs/stable/distributed.html) for details on how to connect these. Likely you will need to use a `tcp://` connection.
