### ISSUE TITLE
Global variables not getting updated under functions with @mpc.run_multiprocess decorator

### ISSUE THREAD

**Issue by anmolagarwalcp810** [facebookresearch/CrypTen#302]
When training models, we needed to store values of losses in loss_array and we had done it in two ways:

1. We had made it global so that it gets updated inside @mpc.run_multiprocess function, but it was not getting updated.
2. We had tried returning loss_array from the same function, but we were getting ConnectionRefusedError: [Errno 111] Connection refused.

Not only loss_array, we also needed few other variables to be returned from the function and were facing the similar issue with those variables as well.

[Notebook](https://github.com/anmolagarwalcp810/Jupyter_Notebooks/blob/main/Issue_302.ipynb) contains the code describing the issue.

Please help.

Method of installing crypten:

git clone https://github.com/facebookresearch/CrypTen.git
cd path/to/Crypten
python setup.py build
python setup.py install

Python version was 3.7 and Anaconda environment was used.

**Comment by knottb** [comment]
To give some context:

1. global variables will not get updated by code inside of `@mpc.run_multiprocess` blocks because these blocks run in different processes and the global variable state is only updated in those processes.

2. There are certain objects that seem to cause this when returned. I think that this error will occur if you try to return a PyTorch tensor (or object containing PyTorch tensors), though it has been a while since I have tested this explicitly. Try returning an array of floats instead?

I hope this helps. Let me know if this works or if there are still issues with this.

**Comment by anmolagarwalcp810** [comment]
Thanks a lot for the help.

For point 2, when I tried returning NumPy array instead of PyTorch tensors, there was no "connection refused" error. Thanks for the suggestion.
