### ISSUE TITLE
Questions about sort, norm, if statement

### ISSUE THREAD

**Issue by amyzx** [facebookresearch/CrypTen#330]
Hi, I have 3 questions about CrypTen. 
      
1. I hope to sort a list of tuple. However, I cannot assign a tuple item seperately or multiply **b** with strings like **apple**. I also tried to use dict which contains **Cryptensor** as the key, string as the value. But it gives me **KeyError**. Is there any other way to implement this function? 

```
def swap_sort(arr): 
    x_len = len(arr)
    for i in range(x_len):
        for j in range(i + 1, x_len):
            compare_and_swap(i, j, arr, True) 

def compare_and_swap(i, j, arr, dir):
    '''compare arr[i] and arr[j], dir: acscending or descending'''
    b = (arr[i][0] < arr[j][0])

    smaller = b * arr[i] + (1 - b) * arr[j]
    larger = arr[i] + arr[j] - smaller
    if dir:   
        arr[i], arr[j] = smaller, larger  # how could I swap the second item?
    else:
        arr[i], arr[j] = larger, smaller
 
def test_sort():
    arr = [ (crypten.cryptensor(2), 'apple'), 
            (crypten.cryptensor(3), 'banana'), 
            (crypten.cryptensor(4), 'orange'), 
            (crypten.cryptensor(1), 'fruit')]
    swap_sort(arr)
```

2. I hope to calculate euclidean distance which is norm-2 distance. But I find that when the number is larger, the norm result will be wrong because **sqrt** does not work well. Could you give me some suggestions how to compute correct norm values?

```
def test_norm(): 
    for item in range(20):
        x = crypten.cryptensor(item) 
        print(x.get_plain_text(), x.square().sum().get_plain_text())
        print(x.get_plain_text(), x.norm().get_plain_text())
        print()
```
This is my result.
![image](https://user-images.githubusercontent.com/8285571/142373385-9404c281-3113-4bac-9879-c2f4e25754a5.png)

3. I hope to use the result of **if** condition. For example, in the following code, **count** is related to the compare result, but I don't know how to update this value using **b**. I could use **if b.get_plain_text() == 1** to replace **if x < y** condition, but this will reveal the compare result.
```
def test_if():
    x = crypten.cryptensor(100) 
    y = crypten.cryptensor(50)
    count = 0

    # if x < y:
    #    count += 1
    #    tmp = x
    #    x = y
    #    y = tmp

    b = (x < y)

    smaller = b * x + (1 - b) * y
    larger = x + y - smaller
    x, y = smaller, larger
    print(x, y)
```

Looking forward to your reply. Thanks a lot!

**Comment by knottb** [comment]
1. There is a way to do this, but it is not as straightforward as your implementation. Because the string value in your tuple is plaintext, the ordering of the strings reveals information about the encrypted tensors, so crypten does not really support this behavior natively.

You would want to encode the strings as values, then encrypt these strings along with the keys. E.g.:

```
def compare_and_swap(i, j, arr):
    # Assuming arr[:][0] contains keys and arr[:][1] contains values
    key_i, val_i = arr[i][0], arr[i][1]
    key_j, val_j = arr[j][0], arr[j][1]
    
    # compare the values
    comp = key_i < key_j
    
    # Swap the keys and values as desired
    arr[i][0] = crypten.where(comp, key_i, key_j)
    arr[i][1] = crypten.where(comp, val_i, val_j)
    arr[j][0] = crypten.where(comp, key_j, key_i)
    arr[j][1] = crypten.where(comp, val_j, val_i)
```
This can be done with fewer rounds of communication by vectorizing the key-value pairs (i.e. by storing them in the same tensor)


2. Numerical instability is introduced by the approximations we use for sqrt here. The function is numerically stable up to an input of approximately 150. Beyond this, special care should be taken. One method is to multiply by a fixed constant at the input and output using the following identity:

`norm(x) = (1 / a) * norm(a * x)`

Using a value of `a` that is less than 1 will give you better numerical stability at the higher range. We do not currently implement this in crypten because the increased dynamic range at the high end comes at the cost of higher quantization error, which causes issues in the low end (values near zero)


3. In general, we cannot use `if` statements conditioned on encrypted values because the code path would reveal the result of the condition. Instead, we must run all conditional paths and multiplex the results based on the condition. For example:

```
if x < y:
   z = f(x)
else:
   z = f(y)
```

This code can be executed in practice by computing both `f(x)` and `f(y)` and multiplexing between these values using `x < y` as follows:

```
z = crypten.where(x < y, f(x), f(y))`
```

FYI, under the hood, `crypten.where` implements the multiplex function as follows:

```
def where(condition, x, y):
    return condition * x + (1 - condition) * y
```
     
     
Let me know if you have other questions.

**Comment by amyzx** [comment]
@knottb  Thanks a lot! Your reply is clear and really helpful!
