### ISSUE TITLE
Question: Will HE or enclave based solution be supported?

### ISSUE THREAD

**Issue by yang8621** [facebookresearch/CrypTen#338]
"CrypTen currently implements a cryptographic method called secure multiparty computation (MPC), and we expect to add support for homomorphic encryption and secure enclaves in future releases. " [The information](https://ai.facebook.com/blog/crypten-a-new-research-tool-for-secure-machine-learning-with-pytorch) was published in 2019.

Could you share the latest information?
Is there any plan to provide the enclave-based solution like Intel SGX or any others? 
Will HE or secure enclave be the parallel solution or combined use with SMPC?

Thanks.

**Comment by knottb** [comment]
Hi, thanks for this question.

We built CrypTen with the intention of eventually adding HE / TEE-based solutions. We do not have a near-term plan to integrate these features directly. However, we did refactor the design of CrypTen to allow for minimal CrypTensor registration, which would allow for a user to implement their own encrypted tensors with minimal effort. The user need only implement a few base functions and a large amount of additional functionality (autograd, etc.) will automatically work.

For an example, see https://github.com/facebookresearch/CrypTen/blob/main/test/pytorch_backend/pytorch_tensor.py

This file implements a CrypTensor that uses a PyTorch tensor as its backend (i.e. rather than HE or TEE). This new tensor implements several functions (`add, neg, mul, matmul, convNd, conv_transposeNd, _ltz, get_plain_text` and a few other small functions). However, because it is registered as a CrypTensor using the `@register_cryptensor` decorator, it inherits the rest of the functionality in the CrypTen framework.
