### ISSUE TITLE
How to combine Crypten with NAS

### ISSUE THREAD

**Issue by amyzx** [facebookresearch/CrypTen#360]
Hi, I am learning how to combine crypten and NAS (network architecture search). NAS is trying to find an efficient network automatically by training a large network (usually >10 hours with GPU). 

I print the state_dict for this large network, and find it's really complex. So I am not sure whether crypten is suitable for NAS situation.

In my situation, I hope to encrypt a large network which contains nn.ModuleList, nn.ParameterList(), and some functions in nn.parallel. 

Does crypten support these operations? If not, could you give me some suggestions about how to implement similar functions?

Thanks a lot! Looking forward to your reply!

**Comment by knottb** [comment]
In theory, there should be nothing preventing this, however there are a few issues you may run into.

1. We do not currently support nn.parallel. It is possible you could reproduce this functionality on your end if needed as I believe you just want to run multiple network architectures in parallel.

2. Speed - Because CrypTen uses secure MPC in its computations, CrypTen will be significantly slower than PyTorch for similar operations. In practice, we find that on CPU, CrypTen experiences approximately 100x slowdown compared to PyTorch, with somewhat better performance with larger models. GPU processing is supported in CrypTen, but the speedup is not as large as it is in plaintext - we tend to see roughly 10x speedup when switching from CPU to GPU in CrypTen. (This means the gap between PyTorch CPU and CrypTen GPU can be roughly 10x).

Given these issues, you may want to consider some benchmarking to determine whether running NAS is likely to complete in a reasonable timeframe.

**Comment by amyzx** [comment]
Thanks a lot!

**Comment by amyzx** [comment]
Hi, sorry to bother you again. I hope to implement torch.nn.ParamterList and torch.nn.ModuleList in CrypTen.
Could you give me some suggestions about how to implement these functions in CrypTen? For example, which source code in CrypTen should I modify? Thanks a lot!

**Comment by knottb** [comment]
`torch.nn.ModuleList` is already implemented in `crypten.nn.ModuleList` [here](https://github.com/facebookresearch/CrypTen/blob/main/crypten/nn/module.py#L793-L848).

The code for PyTorch ParameterList and ParameterDict is [here](https://pytorch.org/docs/stable/_modules/torch/nn/modules/container.html#ParameterList).

I believe you can probably copy this code into `crypten/nn/module.py` [here](https://github.com/facebookresearch/CrypTen/blob/main/crypten/nn/module.py) and update `crypten/nn/__init__.py` [here](https://github.com/facebookresearch/CrypTen/blob/main/crypten/nn/__init__.py) to get the functionality in crypten.

Let me know if this works.

**Comment by amyzx** [comment]
Hi, I have added ParamterList in module.py which uses crypten.nn.Parameter. 

I wrote a model class A which inherits crypten.nn.Module. This model class A has a parameter list which contains serveral crypten.nn.Parameter. But when I try to encrypt this model A, it give me the following error which happens in crypten.nn.Module class.

return self._apply(lambda m: m.encrypt(mode=mode, src=src))
AttributeError: 'Parameter' object has no attribute 'encrypt'

**Comment by knottb** [comment]
I imagine it should inherit the `encrypt` function from `Module` [here](https://github.com/facebookresearch/CrypTen/blob/main/crypten/nn/module.py#L470-L504).

However, seeing that this is not the case, one could add a brief `encrypt` function [here](https://github.com/facebookresearch/CrypTen/blob/main/crypten/nn/module.py#L926-L960) that looks like:

```
def encrypt(self, mode=True, src=0):
    if mode and not self.encrypted:
        self.data = crypten.cryptensor(self.data, src=src)
    elif not mode and self.encrypted:
        self.data = self.data.get_plain_text()
    self.encrypted = mode
    return self
```

**Comment by amyzx** [comment]
Hi, I found that it's my fault. My model class inherits `crypten.nn.Module`, but it contains another model which inherits `torch.nn.Module` in another file. I guess this kind of mix results in this AttributeError. 

When I change all models to inherit `crypten.nn.Module`, it works well.  Yes, `Parameter` inherits the encrypt function from `Module` and we don't need to add `encrypt` function in this class.  

When printing the model's `state_dict`, I found `crypten.nn.BatchNorm2d` is different with `torch.nn.BatchNorm2d`. 

1. In crypten, BatchNorm2d does not have a parameter `affine`.  In pytorch, BatchNorm2d has a parameter affine.
2. In crypten, state_dict are `odict_keys(['conv1.weight', 'conv2.weight', 'bn.weight', 'bn.bias', 'bn.running_mean', 'bn.running_var'])`.  In pytorch, state_dicts are `odict_keys(['running_mean', 'running_var', 'num_batches_tracked'])`. 

Does these differences matter?
