### ISSUE TITLE
"IF" or "Selection" operation use crypten

### ISSUE THREAD

**Issue by MinQinxy** [facebookresearch/CrypTen#371]
I have know it needs to use  (  result = cdt * A + (1- cdt) * B ) for selecting the retsult of A or B. But, I just have a problem about how to implement that in this condition(  it's just an example ):
```python
def f( lst ) :
    # assert  lst != empty
    res = []
    for d in lst:
        if d > 5:   # the filter condition
            res.append(d)
    return res
```
How can I get the crypten version function , "def f(lst: crypten.Cryptensor) -> crypten.Cryptensor" ? or give me some suggestion to solve this problem.

**Comment by knottb** [comment]
This type of behavior can't be achieved using MPC. The reason for this is knowledge of the size of `res` will expose information about the values in `lst`. This information is protected under the privacy guarantees of CrypTen.

If there is a specific use-case for this, there may be an application specific workaround, but typically, we can only provide outputs that are encrypted values. We could also do something like populating `res` with the largest `k` elements of `lst`, but `k` must be static in this case (i.e. we can't branch conditionally based on encrypted values since).

**Comment by MinQinxy** [comment]
Ok, I've got it. Thanks for answer.
