### ISSUE TITLE
Inference with CrypTen-encrypted pre-trained PyTorch model on unencrypted data

### ISSUE THREAD

**Issue by sihohan** [facebookresearch/CrypTen#379]
Hello,

I was wondering whether it is possible to make predictions on unencrypted data using an encrypted pre-trained PyTorch model.
Or does CrypTen require that both the data and the model be encrypted for inference?

Thanks.

**Comment by knottb** [comment]
This is not currently supported. This functionality is not difficult in theory, but due to implementation details, it is difficult to make work inside of CrypTen. We recognize that this is a feature that might be useful, but the implementation would require major refactors to how the NN module works within the CrypTen codebase, so we do not plan on writing an implementation in the short-term.
