### ISSUE TITLE
Why the running times of operators on two hosts are quite different?

### ISSUE THREAD

**Issue by hobbitlzy** [facebookresearch/CrypTen#401]
I am running the following script on two hosts. The running times on two hosts are almost the same using the `comm.get().barrier()`, but they can bequite different without the synchronization.  Since I want to profile the running time of the operators, so I am curious whether should I add the synchronization lines. And if not, why the times are different and which time should I refer to.  Looking forward to your reply.

```python
def test_time():
    crypten.init()
    torch.manual_seed(1)
    
    layer1=crypten.nn.Linear(2000,1000).encrypt(src=0)
    layer2=crypten.nn.ReLU().encrypt(src=0)
    
    inputs=torch.rand((256,2000))
    inputs_enc=crypten.cryptensor(inputs)
    
    start1=timeit.default_timer()
    outputs=layer1(inputs_enc)
    # comm.get().barrier()
    print("Layer1 time:", timeit.default_timer() - start1)
    start=timeit.default_timer()
    outputs=layer2(outputs)
    # comm.get().barrier()
    print("Layer2 time:", timeit.default_timer() - start)
    print("Total time:", timeit.default_timer() - start1)
```
BTW, the total times with or without the synchronization are similar.

**Comment by lvdmaaten** [comment]
If you measure without synchronization, then you may not be measuring the actual time for an operation to complete because many of the computations may be asynchronous -- only certain communications (for example, calling `get_plain_text`) or adding an actual barrier will help you make sure that your timings are actually accurate.
