### ISSUE TITLE
Feature: Mimic Delphi online inference

### ISSUE THREAD

**Issue by ntlm1686** [facebookresearch/CrypTen#420]
##  Feature

Running privacy inference under Delphi.

We only need to support Delphi-like Linear operations, where the weight is not secret-shared. Below is a simple case of a linear layer that can be used to mimic the online inference phase of Delphi:
```python
from crypten.mpc.mpc import MPCTensor
from crypten.mpc.primitives import ArithmeticSharedTensor
from typing import Tuple


class Linear:
    def __init__(
            self,
            weight: torch.Tensor,
            output_shape: Tuple[int, int, int],
            src: int = 0,
            device: str = "cpu", 
    ):
        self.weight = weight  # this should be only visible to its holder
        self.share = ArithmeticSharedTensor.PRZS(output_shape, device=device).share

    def forward(self, x: MPCTensor):
        x = x.matmul(self.weight)
        x.share += self.share
        return x

```

The weight is protected by `self.share` with additive secret sharing.
Preprocessing is currently skipped, such as $W_{server}(HE(r_{client}))$.

Please correct me if I am wrong, and let me know how can we do this better if we want to add this as a feature to CrypTen.

**Comment by ljjsalt** [comment]
Hi @lvdmaaten , could you please take a look?

**Comment by lvdmaaten** [comment]
This seems reasonable, but we wouldn't want to be able to land this in CrypTen as-is for two reasons: 

1. You have a leaky abstraction here. The `Module`s in `crypten.nn` are designed to not make any assumptions on what the underlying cryptographic protocol is. This enables users to implement their own cryptographic protocol and plug it into CrypTen. Your code snippet is clearly making assumptions on the underlying protocol.
2. The code is assuming that we are operating in the two-party regime, which may not be the case.

It also isn't completely clear to me how one would integrate this cleanly into CrypTen. The only think I can imagine is adding custom logic in `crypten.nn.Linear` that switches to the Delphi if we are: (1) in the two-party regime, (2) `Module.train` is set to `False` because the `Module.eval()` function was called, and (3) `x` is actually an `MPCTensor`. Special cases like this tend to get murky pretty quickly though. 

My suggestion would be to keep this as user-side code for now. You probably want to add something like `assert crypten.comm.get().get_world_size() == 2` to catch issues due to 2.

**Comment by ljjsalt** [comment]
@lvdmaaten Thanks a lot for the suggestions. I will probably put the code in a separate repository, so people can use it for experiments with Delphi.
