### ISSUE TITLE
crypten.init() can't establish connection

### ISSUE THREAD

**Issue by ZJG0** [facebookresearch/CrypTen#432]
I used three machines in the LAN to  establish connection, it worked, however, when i can't establish connection with three machines in the WAN. I have closed the firewall and established connection by socket.

**Comment by mohammad-alrubaie** [comment]
I believe if you can establish the LAN connection, it should naturally extend to the WAN case. There are examples in the repo for [launching CrypTen instances in AWS](https://github.com/facebookresearch/CrypTen/blob/13a88f9f1b58ac3f9b5a3a29417e3e56fe04d2f3/scripts/aws_launcher.py). You can probably take a look at the script to see if there are some missing environment variables or other setting requirements. 
If that doesn't resolve the issue, please share more details on the setup in the LAN case, and how it differs from your WAN case.

**Comment by ZJG0** [comment]
The method to establish connection in the examples is different from mine. 

party A: 32.54.32.672/192.168.1.2
party B:76.32.32.754/192.168.1.3
party C:698.52.132.98/192.168.1.4

When I intend to establish LAN connection, the command will be conducted in three machines respectively.
```
RENDEZVOUS=tcp://192.168.1.2:2345 WORLD_SIZE=3 RANK=0 python evaluatePerformance.py
RENDEZVOUS=tcp://192.168.1.2:2345  WORLD_SIZE=3 RANK=1 python evaluatePerformance.py
RENDEZVOUS=tcp://192.168.1.2:2345  WORLD_SIZE=3 RANK=2 python evaluatePerformance.py
```

WAN
```
RENDEZVOUS=tcp://32.54.32.672:2345 WORLD_SIZE=3 RANK=0 python evaluatePerformance.py
RENDEZVOUS=tcp://32.54.32.672:2345  WORLD_SIZE=3 RANK=1 python evaluatePerformance.py
RENDEZVOUS=tcp://32.54.32.672:2345  WORLD_SIZE=3 RANK=2 python evaluatePerformance.py
```

**Comment by mohammad-alrubaie** [comment]
Sorry for the late reply, it looks fine to me. I would also add `MASTER_ADDR=32.54.32.672` and `MASTER_PORT=2345`, but not sure if these are required, and `RENDEZVOUS` might be sufficient. 
I had a run on AWS a while back, and it didn't work initially because I forgot to allow traffic to the given port. It might be permissions issue. 
If this doesn't resolve it, please share the error you receive. We might be able to identify the line of code raising the error.
