### ISSUE TITLE
Why the binary share value not with a 0/1 form ?

### ISSUE THREAD

**Issue by Wangxinqian** [facebookresearch/CrypTen#436]
Is there any way to take the i-th binary value from one of the party?
For example, I create a binary 3PC secret share of some value x. Then, each party should have something like P1=0101010101, P2=0101010101, and P3=011000111. I want to get the index of 3 for party P1 such that P1[3]=1. Is there such way to print the value?
<img width="724" alt="image" src="https://user-images.githubusercontent.com/35109234/204464134-50060ab2-ab12-41e9-b9bd-b839315c8b34.png">

**Comment by mohammad-alrubaie** [comment]
When generating the secret shares for a number, PZRS is [used](https://github.com/facebookresearch/CrypTen/blob/main/crypten/mpc/primitives/binary.py#L91), and part of the process involves [generating a k-bit random number for each party (k = 64 here)](https://github.com/facebookresearch/CrypTen/blob/main/crypten/mpc/primitives/binary.py#L130). That's why you see the long numbers as shares. 
If you XOR the three numbers, you can get ("decrypt") the plaintext number. An example are the shares: `-745765741233482366 ^ -5230685641187854967 ^ 4813887431333748745 = 2`. 
If you want to get the ith bit of a certain party, you can probably do something like this: `bit = (x_enc._tensor >> bit_index) & 1` (with bit_index starting at 0, of course).

**Comment by Wangxinqian** [comment]
Thanks for your reply, I'd ask two further questions:
1) can I modify the value of k? The k is the length of the fixed-point representation.
2) since k=64, the value of bit_index should set between 0 to 63. however, it still will output some values it i run some codes like "x_enc._tensor >> 88"

**Comment by mohammad-alrubaie** [comment]
1. For k, yes, you can change the bit length, but that requires changing CrypTen code. You can see that the function (`generate_kbit_random_tensor()`)[https://github.com/facebookresearch/CrypTen/blob/efe8edad571be1c586d0d9cefc562d562d4e9aa1/crypten/common/rng.py#L33] takes the argument `bitlength` which defaults to the length of `torch.long` but you can set it to any number. You can pass your `bitlength` of choice (here)[https://github.com/facebookresearch/CrypTen/blob/main/crypten/mpc/primitives/binary.py#L130-L131], and potentially other places where it is relevant, or just set the default `bitlength` value. In any case, there's no config parameter to set, but rather a code change. 
2. Shifting by larger than the data type size would be an undefined behavior in many languages. I don't think it'll throw an error, but you would get different results depending on the language/implementation. This behavior is more about Python and/or pytorch.

**Comment by mialuyao** [comment]
I get a similar problem when I attempt to compute the AND operation on two binary shares, but I am getting unexpected results that are not 0 or 1.

Here is my code:
```
@mpc.run_multiprocess(world_size=2) 
def test(x, a, b):
  x_enc, a_enc, b_enc = secret_sharing(x, a, b)
    cmp_a_x = x_enc.ge(a_enc)
    cmp_x_b = b_enc.ge(x_enc)
    cmp_a_x_share = cmp_a_x.share
    cmp_a_x_binary = BinarySharedTensor(cmp_a_x_share)
    cmp_x_b_share = cmp_x_b.share 
    cmp_x_b_binary = BinarySharedTensor(cmp_x_b_share)
    result_binary = cmp_a_x_binary & cmp_x_b_binary
    rank = comm.get().get_rank()
    crypten.print(f"\nRank {rank}:\n result: {result_binary.get_plain_text()}\n", in_order=True)

```
However, the result I got is:
```
Rank 0:
 result: 7298263103844676100


Rank 1:
 result: 7298263103844676100
```
The result is not in the form of 0 or 1 as I expected.
Can someone explain why this is happening and how I can fix it?

Thank you for your assistance!
