### ISSUE TITLE
Support of group convolution on GPU

### ISSUE THREAD

**Issue by hobbitlzy** [facebookresearch/CrypTen#447]
This [line](https://github.com/facebookresearch/CrypTen/blob/909df45b239198243e365994a86027ab4203b2f6/crypten/cuda/cuda_tensor.py#L195) prints the group convolution is not supported on GPU. I am wondering the reason behind this assertion since the variable `nb` seems to serve the function of the group convolution of this [line](https://github.com/facebookresearch/CrypTen/blob/909df45b239198243e365994a86027ab4203b2f6/crypten/cuda/cuda_tensor.py#L218) .

Also, is there any way that I can perform group convolution using Crypten? What if I only need the inference?

**Comment by lvdmaaten** [comment]
Yeah, this is exactly the reason: in order to perform a regular convolution on GPU, CrypTen is actually performing a group convolution under the hood. The reason is we are using a special implementation that performs the integer computation using multiple floating-point computations that are much faster on GPUs; see Section 5.3 of [the paper](https://arxiv.org/pdf/2109.00984.pdf) for context.

At present, the only way to perform group convolution with CrypTen is by doing it manually: create multiple convolutional layers that expect fewer input channels (and create fewer output channels), send slices of your inputs to their respective layers, and concatenate the results. It is cumbersome and not very efficient (it creates more communication rounds than necessary) but I'm afraid it is the best we have for now.

It should be possible to add support for group convolution by tinkering with the current implementation, so if it is something you want to dig into we'd happily accept a PR :)

**Comment by hobbitlzy** [comment]
Thanks for your reply.
