### ISSUE TITLE
The difference between crypten.cryptensor(x, ptype=crypten.mpc.binary) and BinarySharedTensor ?

### ISSUE THREAD

**Issue by mialuyao** [facebookresearch/CrypTen#514]
I want to conduct XOR on two shares, which have been shared with `crypten.cryptensor(x, ptype=crypten.mpc.binary)  `
However, it shows XOR is not supported on `MPCTensor`.
So, what is the difference between `MPCTensor` and `BinarySharedTensor`? 
Why does the share based on `crypten.cryptensor(x, ptype=crypten.mpc.binary)` not equal `BinarySharedTensor`?

**Comment by knottb** [comment]
It seems like this is just due to MPCTensor not having `__and__` and `__xor__` functions implemented. For the most part, this is because we never really expected binary inputs into MPCTensor, rather int or float values. This could probably be implemented by adding `__and__` and `__xor__` functions in MPCTensor that just convert to binary ptype and use binary operations on the `BinarySharedTensor`. However, we essentially treat `MPCTensor` as a wrapper for `ArthimeticSharedTensor` that handles conversions between arithmetic and binary.

**Comment by mialuyao** [comment]
Thank you for your response, your explanation is very valuable to me.
