### ISSUE TITLE
some problem about Feature Aggregation scenario

### ISSUE THREAD

**Issue by guoqingyu319** [facebookresearch/CrypTen#76]
1.If I have two parties to train a model,how can I predict new data?concat them and then predict?
2.two parties encrypt a same data will get a same result,right?can it be different in Feature Aggregation scenario?

**Comment by knottb** [comment]
1. There are several apparent methods to compute inference in a feature aggregation scenario once a model has been trained using CrypTen, each of which comes with its own privacy guarantees:

(a) Assumption: the model can be decrypted after training and inference samples can be shared without encryption - Here party 2 can send their input data to party 1, who then concatenates the two sets of data and runs inference. 

(b) Assumption: the model can be decrypted after training, but inference samples cannot be shared - Here each party receives the plaintext model by decrypting the model weights after training. For each inference, both parties encrypt their data and concatenate, then compute the inference using the public weights (note that weights being public speeds up the computations and reduces communication required).

(c) Assumption: the model and inference samples cannot be shared - For each inference sample, all data must be encrypted, concatenated, then passed through the encrypted model (as it does during training)

Because of the privacy implications, I imagine scenario (c) would be the most common, though (b) may be useful for cases where model memorization is not a concern.


2. The encryption used here (MPC) uses randomness to generate masks, but computations are deterministic (up to rounding errors). To clarify, by deterministic I mean that once values are decrypted, the result should be deterministic given that the input is deterministic and operations computed on the input are deterministic (i.e. functions are deterministic).


Let me know if these answer your questions.

**Comment by guoqingyu319** [comment]
@knottb thank a lot! yes,you said (c) in my question is what I concern,So I wrote a code section to reload the encrypted model,then to re-predict the train data,but I got a error.My code section and the error like following:
------------------------------------------------------------------------------------------------
#model save  
crypten.save(model,'./model.pkl')

#reload model and to predict train data
model = torch.load('./model.pkl')
model.eval()
 x_alice_enc = crypten.load('./data/alice_train.pth', src=ALICE)
 x_bob_enc = crypten.load('./data/bob_train.pth', src=BOB)

 x_combined_enc = crypten.cat([x_alice_enc, x_bob_enc], dim=2)
 # Reshape to match the network architecture
 x_combined_enc = x_combined_enc.unsqueeze(1)
 x_train = AutogradCrypTensor(x_combined_enc)
 x_output = model(x_train)
 print(x_output.get_plain_text())
--------------------------------------------------------------------------------------------------
error:
_

> **Namespace(backend='gloo', batch_size=10, epochs=2, init_method='tcp://169.254.26.193:23456', learning_rate=0.001, no_cuda=False, rank=0, root='data', world_size=2)
> Traceback (most recent call last):
>   File "distributed_launcher.py", line 166, in <module>
>     main()
>   File "distributed_launcher.py", line 160, in main
>     test()
>   File "distributed_launcher.py", line 120, in test
>     x_output = model(x_train)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/nn/module.py", line 55, in __call__
>     return self.forward(input)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/nn/module.py", line 50, in wrapped_forward
>     return object.__getattribute__(self, "forward")(*args)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/nn/module.py", line 326, in forward
>     output = self._modules[node_to_compute](input)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/nn/module.py", line 55, in __call__
>     return self.forward(input)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/nn/module.py", line 50, in wrapped_forward
>     return object.__getattribute__(self, "forward")(*args)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/nn/module.py", line 773, in forward
>     result = tensor.take(indices, self.dimension)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/autograd_cryptensor.py", line 211, in autograd_forward
>     result = grad_fn.forward(ctx, inputs, **kwargs)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/gradients.py", line 248, in forward
>     return input.take(index, dimension)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/mpc/mpc.py", line 42, in convert_wrapper
>     return func(result, *args, **kwargs)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/mpc/mpc.py", line 1174, in ou_wrapper_function
>     result._tensor = getattr(result._tensor, name)(*args, **kwargs)
>   File "/home/PycharmProjects/distributed_crypten_demo/crypten/mpc/primitives/arithmetic.py", line 478, in take
>     result.share = self.share[all_indices]
> IndexError: index 14679060512768 is out of bounds for dimension 0 with size 4**

--------------------------------------------------------------------------------------------
t works if the code section like this:

#model save  
model.decrypt()
crypten.save(model,'./model.pkl')

#reload model and to predict train data
model = torch.load('./model.pkl')
model.encrypt()
model.eval()
 x_alice_enc = crypten.load('./data/alice_train.pth', src=ALICE)
 x_bob_enc = crypten.load('./data/bob_train.pth', src=BOB)

 x_combined_enc = crypten.cat([x_alice_enc, x_bob_enc], dim=2)
 # Reshape to match the network architecture
 x_combined_enc = x_combined_enc.unsqueeze(1)
 x_train = AutogradCrypTensor(x_combined_enc)
 x_output = model(x_train)
 print(x_output.get_plain_text())

So what is the problem? I guess when I use crypten,init() in test part,the random value of encrypt is changed,so the encrypted model doesn't work,right？
